from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QScrollBar, QMainWindow, QHBoxLayout, QVBoxLayout, QWidget, QGridLayout, QStatusBar, QLabel, QPushButton, QLineEdit, QTextEdit, QSpinBox, QDoubleSpinBox, QToolBar
from PyQt6 import QtCore, QtGui
from PyQt6.QtGui import QPixmap
import pandas as pd
from recommendationModel import RecommendationModel
import sys
import spotipy
import spotipy.util as util
from spotipy.oauth2 import SpotifyClientCredentials
import os
import re
import json
import os.path
from datetime import datetime
import time
import imageio
from scipy import ndimage, spatial
from PIL import Image, ImageDraw
import PIL as pillow
import requests
from io import BytesIO
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # Authorization
        scope = 'user-read-private user-library-read user-read-playback-state user-modify-playback-state user-top-read playlist-modify-private playlist-modify-public'
        token = util.prompt_for_user_token(scope=scope, client_id='#CLIENTID',client_secret='#CLIENTSECRET', redirect_uri='#REDIRECTURI')
        self.sp = spotipy.Spotify(auth=token,requests_timeout=10, retries=10)

        # Main interface
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 737)
        MainWindow.setStyleSheet("#menuBar{\n""    background:#000;\n""    color:#fff;\n""}\n""#menuProfile{\n""    float:right;\n""    text-align:right;\n""}\n""#home, #search, #playing{\n""    background:#1e1e1e;\n""}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#menu{\n""    background:#000;\n""}\n""#main{\n""    background:#1e1e1e;\n""}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.main.setObjectName("main")
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Menu Bar Interface
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1029, 26))
        self.menuBar.setObjectName("menuBar")
        self.mainMenu = QtWidgets.QMenu(parent=self.menuBar)
        self.mainMenu.setObjectName("mainMenu")
        self.mainMenu.setTitle("...")
        self.playbackMenu = QtWidgets.QMenu(parent=self.menuBar)
        self.playbackMenu.setObjectName("playbackMenu")
        self.playbackMenu.setTitle("Playback")
        self.play_action = QtGui.QAction('Play', self)
        self.pause_action = QtGui.QAction('Pause', self)
        self.next_action = QtGui.QAction('Next', self)
        self.prev_action = QtGui.QAction('Previous', self)
        self.playbackMenu.addAction(self.play_action)
        self.playbackMenu.addAction(self.pause_action)
        self.playbackMenu.addAction(self.next_action)
        self.playbackMenu.addAction(self.prev_action)
        self.volumeMenu = QtWidgets.QMenu(parent=self.menuBar)
        self.volumeMenu.setTitle("Volume")
        self.action100 = QtGui.QAction('100', self)
        self.action80 = QtGui.QAction('80', self)
        self.action60 = QtGui.QAction('60', self)
        self.action40 = QtGui.QAction('40', self)
        self.action20 = QtGui.QAction('20', self)
        self.action0 = QtGui.QAction('Mute', self)
        self.volumeMenu.addAction(self.action100)
        self.volumeMenu.addAction(self.action80)
        self.volumeMenu.addAction(self.action60)
        self.volumeMenu.addAction(self.action40)
        self.volumeMenu.addAction(self.action20)
        self.volumeMenu.addAction(self.action0)
        MainWindow.setMenuBar(self.menuBar)
        self.mainMenu.addAction(self.playbackMenu.menuAction())
        self.mainMenu.addAction(self.volumeMenu.menuAction())
        self.menuBar.addAction(self.mainMenu.menuAction())
        
        # Left Menu Interface
        self.menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.menu.setMinimumSize(QtCore.QSize(220, 0))
        self.menu.setObjectName("menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.menuTop = QtWidgets.QWidget(parent=self.menu)
        self.menuTop.setObjectName("menuTop")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menuTop)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.homeButton = QtWidgets.QPushButton(parent=self.menuTop, text="Home")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("background:#000;color:#fff;")
        icon = QtGui.QIcon()
        pixmap = QtGui.QPixmap('assets/search.svg')
        scaledP = pixmap.scaled(50,50)
        icon.addPixmap(scaledP, QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton.setIcon(QtGui.QIcon('assets/home.svg'))
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_5.addWidget(self.homeButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.msearchButton = QtWidgets.QPushButton(parent=self.menuTop, text="Search")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.msearchButton.setFont(font)
        self.msearchButton.setStyleSheet("background:#000;color:#fff;")
        self.msearchButton.setIcon(QtGui.QIcon(scaledP))
        self.msearchButton.setObjectName("msearchButton")
        self.verticalLayout_5.addWidget(self.msearchButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.playingButton = QtWidgets.QPushButton(parent=self.menuTop, text="Playing")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.playingButton.setFont(font)
        self.playingButton.setStyleSheet("background:#000;color:#fff;")
        self.playingButton.setIcon(QtGui.QIcon('assets/playing.svg'))
        self.playingButton.setObjectName("playingButton")
        self.verticalLayout_5.addWidget(self.playingButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.libraryButton = QtWidgets.QPushButton(parent=self.menuTop, text="Library")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.libraryButton.setFont(font)
        self.libraryButton.setStyleSheet("background:#000;color:#fff;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconPack/disc.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.libraryButton.setIcon(QtGui.QIcon('assets/library.svg'))
        self.libraryButton.setObjectName("libraryButton")
        self.verticalLayout_5.addWidget(self.libraryButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addWidget(self.menuTop, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.menuBottom = QtWidgets.QWidget(parent=self.menu)
        self.menuBottom.setObjectName("menuBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menuBottom)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4.addWidget(self.menuBottom, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addWidget(self.menu)
        
        # Home Page Interface
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerHome = QtWidgets.QWidget(parent=self.home)
        self.headerHome.setStyleSheet("#headerHome {background:qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:0, stop:0.144279 rgba(0, 161, 255, 255), stop:0.726368 rgba(0, 255, 143, 255))}")
        self.headerHome.setObjectName("headerHome")
        self.headerHome.setMinimumSize(QtCore.QSize(0, 200))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerHome)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.welcomeWidget = QtWidgets.QWidget(parent=self.headerHome)
        self.welcomeWidget.setObjectName("welcomeWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.welcomeWidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.welcomeLabel = QtWidgets.QLabel(parent=self.welcomeWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(500)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color:#fff;")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.horizontalLayout_11.addWidget(self.welcomeLabel, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.profileWidget = QtWidgets.QWidget(parent=self.welcomeWidget)
        self.profileWidget.setObjectName("profileWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.profileWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profile = QtWidgets.QWidget(parent=self.profileWidget)
        self.profile.setStyleSheet("#profileName{\n""    color:#fff;\n""}")
        self.profile.setObjectName("profile")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.profile)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profilePic = QtWidgets.QLabel(parent=self.profile)
        self.profilePic.setObjectName("profilePic")
        self.horizontalLayout_3.addWidget(self.profilePic, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.profileName = QtWidgets.QLabel(parent=self.profile)
        self.profileName.setObjectName("profileName")
        self.horizontalLayout_3.addWidget(self.profileName, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_2.addWidget(self.profile, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.device = QtWidgets.QWidget(parent=self.profileWidget)
        self.device.setObjectName("device")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.device)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.device, text="Devices: ")
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:#fff;")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.deviceOptions = QtWidgets.QComboBox(parent=self.device)
        self.deviceOptions.setAutoFillBackground(False)
        self.deviceOptions.setStyleSheet("background:#fff;")
        self.deviceOptions.setObjectName("deviceOptions")
        self.horizontalLayout_6.addWidget(self.deviceOptions)
        self.verticalLayout_2.addWidget(self.device, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_11.addWidget(self.profileWidget)
        self.horizontalLayout_2.addWidget(self.welcomeWidget)
        self.verticalLayout.addWidget(self.headerHome)
        self.homePlaylist_1 = QtWidgets.QWidget(parent=self.home)
        self.homePlaylist_1.setObjectName("homePlaylist_1")
        self.vLayout_7 = QtWidgets.QVBoxLayout(self.homePlaylist_1)
        self.vLayout_7.setContentsMargins(0, 0, 0, 0)
        self.vLayout_7.setSpacing(0)
        self.vLayout_7.setObjectName("verticalLayout_7")
        self.topPlaylist = QtWidgets.QLabel(parent=self.homePlaylist_1)
        self.trackinfo = QLabel(parent=self.homePlaylist_1)
        self.trackinfo.setMaximumSize(QtCore.QSize(16777215, 60))
        self.trackinfo.setMinimumSize(QtCore.QSize(0, 60))
        self.trackinfo.setFont(font)
        self.trackinfo.setStyleSheet("color:#fff;\n""border-bottom:1px")
        self.trackinfo.setObjectName("track")
        self.vLayout_7.addWidget(self.trackinfo, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_27 = QHBoxLayout(self.trackinfo)
        self.horizontalLayout_27.setObjectName("horizontalLayout_23")
        self.serialInfo = QLabel(parent=self.trackinfo)
        self.serialInfo.setObjectName("trackartLabel")
        self.serialInfo.setMaximumSize(QtCore.QSize(60, 40))
        self.serialInfo.setMinimumSize(QtCore.QSize(30, 40))
        self.serialInfo.setText("#")
        self.horizontalLayout_27.addWidget(self.serialInfo)
        self.trackartLabelInfo = QLabel(parent=self.trackinfo)
        self.trackartLabelInfo.setObjectName("trackartLabel")
        self.trackartLabelInfo.setMaximumSize(QtCore.QSize(40, 40))
        self.trackartLabelInfo.setMinimumSize(QtCore.QSize(40, 40))
        self.trackartLabelInfo.setText("")
        self.horizontalLayout_27.addWidget(self.trackartLabelInfo)
        self.trackNameLabelInfo =QLabel(parent=self.trackinfo)
        self.trackNameLabelInfo.setObjectName("trackNameLabel")
        self.trackNameLabelInfo.setText("Title")
        self.trackNameLabelInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.trackNameLabelInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_27.addWidget(self.trackNameLabelInfo)
        self.tartistNameLabelInfo = QLabel(parent=self.trackinfo)
        self.tartistNameLabelInfo.setObjectName("tartistNameLabel")
        self.tartistNameLabelInfo.setText("Artist")
        self.tartistNameLabelInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.tartistNameLabelInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_27.addWidget(self.tartistNameLabelInfo)
        self.albumNameInfo = QLabel(parent=self.trackinfo)
        self.albumNameInfo.setObjectName("albumName")
        self.albumNameInfo.setText("Album")
        self.albumNameInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.albumNameInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_27.addWidget(self.albumNameInfo)
        self.dateAddedInfo = QLabel(parent=self.trackinfo)
        self.dateAddedInfo.setObjectName("dateAdded")
        self.dateAddedInfo.setText("Release Date")
        self.dateAddedInfo.setMaximumSize(QtCore.QSize(170, 40))
        self.dateAddedInfo.setMinimumSize(QtCore.QSize(70, 40))
        self.horizontalLayout_27.addWidget(self.dateAddedInfo)
        self.trackHome=[]
        play = self.sp.playlist_tracks("6cClnm3FshurLsXWBrd0kB")
        playItem = play["items"] #Get songs in the playlist
        for self.i in range(7):
            self.trackHome.append(self.i)
            self.trackHome[self.i] = QPushButton(parent=self.homePlaylist_1)
            self.trackHome[self.i].setMaximumSize(QtCore.QSize(16777215, 60))
            self.trackHome[self.i].setMinimumSize(QtCore.QSize(0, 60))
            self.trackHome[self.i].setFont(font)
            self.trackHome[self.i].setCheckable(True)
            self.trackHome[self.i].setStyleSheet("color:#fff;background:#1e1e1e\n")
            self.trackHome[self.i].setObjectName("track")
            self.vLayout_7.addWidget(self.trackHome[self.i], QtCore.Qt.AlignmentFlag.AlignTop)
            self.horizontalLayout_27 = QHBoxLayout(self.trackHome[self.i])
            self.horizontalLayout_27.setObjectName("horizontalLayout_22")
            self.serial = QLabel(parent=self.trackHome[self.i])
            self.serial.setText(str(self.i+1))
            self.serial.setMaximumSize(QtCore.QSize(40, 40))
            self.serial.setMinimumSize(QtCore.QSize(40, 40))
            self.horizontalLayout_27.addWidget(self.serial)
            self.trackartLabel = QLabel(parent=self.trackHome[self.i])
            self.trackartLabel.setObjectName("trackartLabel")
            self.trackartLabel.setMaximumSize(QtCore.QSize(60, 40))
            self.trackartLabel.setMinimumSize(QtCore.QSize(60, 40))
            trackName = playItem[self.i]['track']['name']
            trackName = "".join(x for x in trackName if x.isalpha())
            if os.path.isfile('images/'+trackName + '.png'):
                pixmap = QPixmap("images/"+trackName + '.png')
                self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
            else:
                try:
                    response = requests.get(playItem[self.i]['track']['album']['images'][0]['url'])
                    img2 = Image.open(BytesIO(response.content))
                    imageio.imwrite('images/'+ trackName + '.png', img2)
                    pixmap = QPixmap("images/"+ trackName + '.png')
                    self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
                except requests.exceptions.Timeout:
                    print ("Timeout occurred")
            self.horizontalLayout_27.addWidget(self.trackartLabel)
            self.trackNameLabel =QLabel(parent=self.trackHome[self.i])
            self.trackNameLabel.setObjectName("trackNameLabel")
            self.trackNameLabel.setText(playItem[self.i]['track']['name'])
            self.trackNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.trackNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_27.addWidget(self.trackNameLabel)
            self.tartistNameLabel = QLabel(parent=self.trackHome[self.i])
            self.tartistNameLabel.setObjectName("tartistNameLabel")
            self.tartistNameLabel.setText(playItem[self.i]['track']['artists'][0]['name'])
            self.tartistNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.tartistNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_27.addWidget(self.tartistNameLabel)
            self.albumName = QLabel(parent=self.trackHome[self.i])
            self.albumName.setObjectName("albumName")
            self.albumName.setMaximumSize(QtCore.QSize(270, 40))
            self.albumName.setMinimumSize(QtCore.QSize(170, 40))
            self.albumName.setText(playItem[self.i]['track']['album']['name'])
            self.horizontalLayout_27.addWidget(self.albumName)
            self.dateAdded = QLabel(parent=self.trackHome[self.i])
            self.dateAdded.setObjectName("dateAdded")
            self.dateAdded.setMaximumSize(QtCore.QSize(170, 40))
            self.dateAdded.setMinimumSize(QtCore.QSize(100, 40))
            self.dateAdded.setText(playItem[self.i]['track']['album']['release_date'])
            self.horizontalLayout_27.addWidget(self.dateAdded)
            self.trackHome[self.i].clicked.connect(lambda a=self.i: self.checkHButtonChecked(a))
        self.verticalLayout.addWidget(self.homePlaylist_1)
        self.main.addWidget(self.home)

        # Playing page Interface
        self.nowPlaying = QtWidgets.QWidget()
        self.nowPlaying.setStyleSheet("#nowPlaying{\n""    background:#1e1e1e;\n""}")
        self.nowPlaying.setObjectName("nowPlaying")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.nowPlaying)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.playingHeader = QtWidgets.QWidget(parent=self.nowPlaying)
        self.playingHeader.setMaximumSize(QtCore.QSize(16777215, 200))
        self.playingHeader.setMinimumSize(QtCore.QSize(0, 200))
        self.playingHeader.setStyleSheet("#playingHeader {background:qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:0, stop:0.144279 rgba(0, 161, 255, 255), stop:0.726368 rgba(0, 255, 143, 255))}")
        self.playingHeader.setObjectName("playingHeader")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.playingHeader)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.playingText = QtWidgets.QLabel(parent=self.playingHeader, text="Now Playing")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(500)
        self.playingText.setFont(font)
        self.playingText.setStyleSheet("color:#fff;")
        self.playingText.setObjectName("playingText")
        self.horizontalLayout_4.addWidget(self.playingText, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_7.addWidget(self.playingHeader)
        self.bodyPlaying = QtWidgets.QWidget(parent=self.nowPlaying)
        self.bodyPlaying.setObjectName("bodyPlaying")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.bodyPlaying)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.albumArt = QtWidgets.QWidget(parent=self.bodyPlaying)
        self.albumArt.setObjectName("albumArt")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.albumArt)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.albumArtLabel = QtWidgets.QLabel(parent=self.albumArt)
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.verticalLayout_9.addWidget(self.albumArtLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_8.addWidget(self.albumArt)
        self.songSection = QtWidgets.QWidget(parent=self.bodyPlaying)
        self.songSection.setObjectName("songSection")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.songSection)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.songInfo = QtWidgets.QWidget(parent=self.songSection)
        self.songInfo.setObjectName("songInfo")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.songInfo)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.songName = QtWidgets.QLabel(parent=self.songInfo)
        self.songName.setStyleSheet("color:#fff;")
        self.songName.setObjectName("songName")
        self.verticalLayout_10.addWidget(self.songName)
        self.artistName = QtWidgets.QLabel(parent=self.songInfo)
        self.artistName.setStyleSheet("color:#fff;")
        self.artistName.setObjectName("artistName")
        self.verticalLayout_10.addWidget(self.artistName)
        self.verticalLayout_11.addWidget(self.songInfo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.player = QtWidgets.QWidget(parent=self.songSection)
        self.player.setObjectName("player")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.player)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.prevSong = QtWidgets.QPushButton(parent=self.player)
        self.prevSong.setMaximumSize(QtCore.QSize(30, 50))
        self.prevSong.setStyleSheet("    background: #1db954;")
        self.prevSong.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconPack/skip-back.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.prevSong.setIcon(QtGui.QIcon('assets/prev.svg'))
        self.prevSong.setObjectName("prevSong")
        self.horizontalLayout_21.addWidget(self.prevSong)
        self.pausePlayButton = QtWidgets.QPushButton(parent=self.player)
        self.pausePlayButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pausePlayButton.setStyleSheet("    background: #1db954;")
        self.pausePlayButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconPack/pause.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pausePlayButton.setIcon(QtGui.QIcon('assets/pause.svg'))
        self.pausePlayButton.setObjectName("pausePlayButton")
        self.horizontalLayout_21.addWidget(self.pausePlayButton)
        self.nextSong = QtWidgets.QPushButton(parent=self.player)
        self.nextSong.setMaximumSize(QtCore.QSize(30, 50))
        self.nextSong.setStyleSheet("    background: #1db954;")
        self.nextSong.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconPack/skip-forward.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.nextSong.setIcon(QtGui.QIcon('assets/next.svg'))
        self.nextSong.setObjectName("nextSong")
        self.horizontalLayout_21.addWidget(self.nextSong)
        self.verticalLayout_11.addWidget(self.player, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_8.addWidget(self.songSection, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget = QtWidgets.QWidget(parent=self.bodyPlaying)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.volSlider = QtWidgets.QSlider(parent=self.widget)
        self.volSlider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.volSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volSlider.setObjectName("volSlider")
        self.horizontalLayout_5.addWidget(self.volSlider)
        self.lyricsSong = QtWidgets.QPushButton(parent=self.widget)
        self.lyricsSong.setMaximumSize(QtCore.QSize(30, 50))
        self.lyricsSong.setStyleSheet("    background: #1db954;")
        self.lyricsSong.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconPack/shuffle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lyricsSong.setIcon(QtGui.QIcon('assets/mic.svg'))
        self.lyricsSong.setObjectName("lyricsSong")
        self.horizontalLayout_5.addWidget(self.lyricsSong)
        self.verticalLayout_8.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_7.addWidget(self.bodyPlaying)
        self.main.addWidget(self.nowPlaying)

        # Search page Interface
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.search)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.searchBody = QtWidgets.QWidget(parent=self.search)
        self.searchBody.setObjectName("searchBody")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.searchBody)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchHeader = QtWidgets.QWidget(parent=self.searchBody)
        self.searchHeader.setObjectName("searchHeader")
        self.searchHeader.setMaximumSize(QtCore.QSize(16777215,200))
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.searchHeader)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.barWidget = QtWidgets.QWidget(parent=self.searchHeader)
        self.barWidget.setStyleSheet("#barWidget{\n""border:1px solid #ddd;\n""}")
        self.barWidget.setObjectName("barWidget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.barWidget)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.searchBox = QtWidgets.QFrame(parent=self.barWidget)
        self.searchBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.searchBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.searchBox)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.searchText = QtWidgets.QLineEdit(parent=self.searchBox)
        self.searchText.setObjectName("searchText")
        self.searchText.setStyleSheet("border-radius:5px;")
        self.horizontalLayout_19.addWidget(self.searchText)
        self.horizontalLayout_18.addWidget(self.searchBox, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.searchButton = QtWidgets.QPushButton(parent=self.barWidget, text="")
        self.searchButton.setObjectName("searchButton")
        self.searchButton.setIcon(QtGui.QIcon('assets/searchBlack.svg'))
        self.searchButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.searchButton.setMinimumSize(QtCore.QSize(60, 0))
        self.searchHeader.setStyleSheet("#searchHeader {background:qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:0, stop:0.144279 rgba(0, 161, 255, 255), stop:0.726368 rgba(0, 255, 143, 255))}")
        self.horizontalLayout_18.addWidget(self.searchButton)
        self.horizontalLayout_16.addWidget(self.barWidget, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.searchHeader)
        self.widget_2 = QtWidgets.QWidget(parent=self.searchBody)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout_17.addWidget(self.searchBody)
        self.main.addWidget(self.search)

        # Library page Interface
        self.library = QtWidgets.QWidget()
        self.library.setStyleSheet("background:#1e1e1e;")
        self.library.setObjectName("library")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.library)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.libraryHeader = QtWidgets.QWidget(parent=self.library)
        self.libraryHeader.setMinimumSize(QtCore.QSize(0, 200))
        self.libraryHeader.setStyleSheet("#libraryHeader {background:qlineargradient(spread:repeat, x1:0, y1:1, x2:1, y2:0, stop:0.144279 rgba(0, 161, 255, 255), stop:0.726368 rgba(0, 255, 143, 255))}")
        self.libraryHeader.setObjectName("libraryHeader")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.libraryHeader)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.libraryText = QtWidgets.QLabel(parent=self.libraryHeader, text="Library")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(500)
        self.libraryText.setFont(font)
        self.libraryText.setStyleSheet("color:#fff;background:none")
        self.libraryText.setObjectName("libraryText")
        self.horizontalLayout_20.addWidget(self.libraryText, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_12.addWidget(self.libraryHeader)
        self.libraryBody = QtWidgets.QWidget(parent=self.library)
        self.libraryBody.setObjectName("libraryBody")
        self.verticalLayout_12.addWidget(self.libraryBody)
        self.main.addWidget(self.library)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.libraryBody)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 807, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_24.setObjectName("horizontalLayout_22")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        try:
            play = self.sp.playlist_tracks("6xCEyZll8DECLNx2rlfvYG") # Get Playlist
        except requests.ReadTimeout:
            play = self.sp.playlist_tracks("6xCEyZll8DECLNx2rlfvYG") # Get Playlist
        playItem = play["items"] #Get songs in the playlist
        self.items = len(playItem) #Get total number of songs
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.trackContainer = QWidget(parent=self.scrollAreaWidgetContents)
        self.trackContainer.setFont(font)
        self.horizontalLayout_24.addWidget(self.trackContainer)
        self.verticalLayout_22 = QVBoxLayout(self.trackContainer)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.trackinfo = QLabel(parent=self.trackContainer)
        self.trackinfo.setMaximumSize(QtCore.QSize(16777215, 60))
        self.trackinfo.setMinimumSize(QtCore.QSize(0, 60))
        self.trackinfo.setFont(font)
        self.trackinfo.setStyleSheet("color:#fff;\n""border-bottom:1px")
        self.trackinfo.setObjectName("track")
        self.verticalLayout_22.addWidget(self.trackinfo, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_23 = QHBoxLayout(self.trackinfo)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.serialInfo = QLabel(parent=self.trackinfo)
        self.serialInfo.setObjectName("trackartLabel")
        self.serialInfo.setMaximumSize(QtCore.QSize(60, 40))
        self.serialInfo.setMinimumSize(QtCore.QSize(30, 40))
        self.serialInfo.setText("#")
        self.horizontalLayout_23.addWidget(self.serialInfo)
        self.trackartLabelInfo = QLabel(parent=self.trackinfo)
        self.trackartLabelInfo.setObjectName("trackartLabel")
        self.trackartLabelInfo.setMaximumSize(QtCore.QSize(40, 40))
        self.trackartLabelInfo.setMinimumSize(QtCore.QSize(40, 40))
        self.trackartLabelInfo.setText("")
        self.horizontalLayout_23.addWidget(self.trackartLabelInfo)
        self.trackNameLabelInfo =QLabel(parent=self.trackinfo)
        self.trackNameLabelInfo.setObjectName("trackNameLabel")
        self.trackNameLabelInfo.setText("Title")
        self.trackNameLabelInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.trackNameLabelInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_23.addWidget(self.trackNameLabelInfo)
        self.tartistNameLabelInfo = QLabel(parent=self.trackinfo)
        self.tartistNameLabelInfo.setObjectName("tartistNameLabel")
        self.tartistNameLabelInfo.setText("Artist")
        self.tartistNameLabelInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.tartistNameLabelInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_23.addWidget(self.tartistNameLabelInfo)
        self.albumNameInfo = QLabel(parent=self.trackinfo)
        self.albumNameInfo.setObjectName("albumName")
        self.albumNameInfo.setText("Album")
        self.albumNameInfo.setMaximumSize(QtCore.QSize(270, 40))
        self.albumNameInfo.setMinimumSize(QtCore.QSize(170, 40))
        self.horizontalLayout_23.addWidget(self.albumNameInfo)
        self.dateAddedInfo = QLabel(parent=self.trackinfo)
        self.dateAddedInfo.setObjectName("dateAdded")
        self.dateAddedInfo.setText("Release Date")
        self.dateAddedInfo.setMaximumSize(QtCore.QSize(170, 40))
        self.dateAddedInfo.setMinimumSize(QtCore.QSize(70, 40))
        self.horizontalLayout_23.addWidget(self.dateAddedInfo)
        self.track=[]
        for self.i in range(len(playItem)):
            self.track.append(self.i)
            self.track[self.i] = QPushButton(parent=self.trackContainer)
            self.track[self.i].setMaximumSize(QtCore.QSize(16777215, 60))
            self.track[self.i].setMinimumSize(QtCore.QSize(0, 60))
            self.track[self.i].setFont(font)
            self.track[self.i].setCheckable(True)
            self.track[self.i].setStyleSheet("color:#fff;\n")
            self.track[self.i].setObjectName("track")
            self.verticalLayout_22.addWidget(self.track[self.i], QtCore.Qt.AlignmentFlag.AlignTop)
            self.horizontalLayout_22 = QHBoxLayout(self.track[self.i])
            self.horizontalLayout_22.setObjectName("horizontalLayout_22")
            self.serial = QLabel(parent=self.track[self.i])
            self.serial.setText(str(self.i+1))
            self.serial.setMaximumSize(QtCore.QSize(40, 40))
            self.serial.setMinimumSize(QtCore.QSize(40, 40))
            self.horizontalLayout_22.addWidget(self.serial)
            self.trackartLabel = QLabel(parent=self.track[self.i])
            self.trackartLabel.setObjectName("trackartLabel")
            self.trackartLabel.setMaximumSize(QtCore.QSize(60, 40))
            self.trackartLabel.setMinimumSize(QtCore.QSize(60, 40))
            trackName = playItem[self.i]['track']['name']
            trackName = "".join(x for x in trackName if x.isalpha())
            if os.path.isfile('images/'+trackName + '.png'):
                pixmap = QPixmap("images/"+trackName + '.png')
                self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
            else:
                try:
                    response = requests.get(playItem[self.i]['track']['album']['images'][0]['url'])
                    img1 = Image.open(BytesIO(response.content))
                    imageio.imwrite('images/'+trackName + '.png', img1)
                    pixmap = QPixmap("images/"+trackName + '.png')
                    self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
                except requests.exceptions.Timeout:
                    print ("Timeout occurred")
            self.horizontalLayout_22.addWidget(self.trackartLabel)
            self.trackNameLabel =QLabel(parent=self.track[self.i])
            self.trackNameLabel.setObjectName("trackNameLabel")
            self.trackNameLabel.setText(playItem[self.i]['track']['name'])
            self.trackNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.trackNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_22.addWidget(self.trackNameLabel)
            self.tartistNameLabel = QLabel(parent=self.track[self.i])
            self.tartistNameLabel.setObjectName("tartistNameLabel")
            self.tartistNameLabel.setText(playItem[self.i]['track']['artists'][0]['name'])
            self.tartistNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.tartistNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_22.addWidget(self.tartistNameLabel)
            self.albumName = QLabel(parent=self.track[self.i])
            self.albumName.setObjectName("albumName")
            self.albumName.setMaximumSize(QtCore.QSize(270, 40))
            self.albumName.setMinimumSize(QtCore.QSize(170, 40))
            self.albumName.setText(playItem[self.i]['track']['album']['name'])
            self.horizontalLayout_22.addWidget(self.albumName)
            self.dateAdded = QLabel(parent=self.track[self.i])
            self.dateAdded.setObjectName("dateAdded")
            self.dateAdded.setMaximumSize(QtCore.QSize(170, 40))
            self.dateAdded.setMinimumSize(QtCore.QSize(100, 40))
            self.dateAdded.setText(playItem[self.i]['track']['album']['release_date'])
            self.horizontalLayout_22.addWidget(self.dateAdded)
            self.track[self.i].clicked.connect(lambda a=self.i: self.checkButtonChecked(a))
        
        self.recommendLabel = QLabel("Recommended Songs:")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recommendLabel.setFont(font)
        self.recommendLabel.setStyleSheet("color:#fff;")
        self.verticalLayout_22.addWidget(self.recommendLabel, QtCore.Qt.AlignmentFlag.AlignTop)
        self.rTracks=[]
        self.recModel = RecommendationModel()
        self.playlist = self.recModel.edm_top40
        self.ids = self.playlist['id'].to_list()
        for self.i in range(5):
            track = self.sp.track(self.ids[self.i])
            self.rTracks.append(self.i)
            self.rTracks[self.i] = QPushButton(parent=self.trackContainer)
            self.rTracks[self.i].setMaximumSize(QtCore.QSize(16777215, 60))
            self.rTracks[self.i].setMinimumSize(QtCore.QSize(0, 60))
            self.rTracks[self.i].setFont(font)
            self.rTracks[self.i].setCheckable(True)
            self.rTracks[self.i].setStyleSheet("color:#fff;\n")
            self.rTracks[self.i].setObjectName("track")
            self.verticalLayout_22.addWidget(self.rTracks[self.i], QtCore.Qt.AlignmentFlag.AlignTop)
            self.horizontalLayout_22 = QHBoxLayout(self.rTracks[self.i])
            self.horizontalLayout_22.setObjectName("horizontalLayout_22")
            self.serial = QLabel(parent=self.rTracks[self.i])
            self.serial.setText(str(self.i+1))
            self.serial.setMaximumSize(QtCore.QSize(40, 40))
            self.serial.setMinimumSize(QtCore.QSize(40, 40))
            self.horizontalLayout_22.addWidget(self.serial)
            self.trackartLabel = QLabel(parent=self.rTracks[self.i])
            self.trackartLabel.setObjectName("trackartLabel")
            self.trackartLabel.setMaximumSize(QtCore.QSize(60, 40))
            self.trackartLabel.setMinimumSize(QtCore.QSize(60, 40))
            trackName = track['name']
            trackName = "".join(x for x in trackName if x.isalpha())
            if os.path.isfile('images/'+trackName + '.png'):
                pixmap = QPixmap("images/"+trackName + '.png')
                self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
            else:
                try:
                    response = requests.get(track['album']['images'][0]['url'])
                    img1 = Image.open(BytesIO(response.content))
                    imageio.imwrite('images/'+trackName + '.png', img1)
                    pixmap = QPixmap("images/"+trackName + '.png')
                    self.trackartLabel.setPixmap(pixmap.scaled(40, 40))
                except requests.exceptions.Timeout:
                    print ("Timeout occurred")
            self.horizontalLayout_22.addWidget(self.trackartLabel)
            self.trackNameLabel =QLabel(parent=self.rTracks[self.i])
            self.trackNameLabel.setObjectName("trackNameLabel")
            self.trackNameLabel.setText(track['name'])
            self.trackNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.trackNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_22.addWidget(self.trackNameLabel)
            self.tartistNameLabel = QLabel(parent=self.rTracks[self.i])
            self.tartistNameLabel.setObjectName("tartistNameLabel")
            self.tartistNameLabel.setText(track['artists'][0]['name'])
            self.tartistNameLabel.setMaximumSize(QtCore.QSize(270, 40))
            self.tartistNameLabel.setMinimumSize(QtCore.QSize(170, 40))
            self.horizontalLayout_22.addWidget(self.tartistNameLabel)
            self.albumName = QLabel(parent=self.rTracks[self.i])
            self.albumName.setObjectName("albumName")
            self.albumName.setMaximumSize(QtCore.QSize(270, 40))
            self.albumName.setMinimumSize(QtCore.QSize(170, 40))
            self.albumName.setText(track['album']['name'])
            self.horizontalLayout_22.addWidget(self.albumName)
            self.dateAdded = QLabel(parent=self.rTracks[self.i])
            self.dateAdded.setObjectName("dateAdded")
            self.dateAdded.setMaximumSize(QtCore.QSize(170, 40))
            self.dateAdded.setMinimumSize(QtCore.QSize(100, 40))
            self.dateAdded.setText(track['album']['release_date'])
            self.horizontalLayout_22.addWidget(self.dateAdded)
            self.rTracks[self.i].clicked.connect(lambda a=self.i: self.checkButtonChecked(a))

        # Lyrics Page
        self.lyricsPage = QtWidgets.QWidget(parent=self.main)
        self.lyricsPage.setStyleSheet("background:#585858")
        self.lyricsPLayout = QtWidgets.QVBoxLayout(self.lyricsPage)
        self.lyricsHeader = QtWidgets.QWidget(parent=self.lyricsPage)
        self.lyricsHeader.setStyleSheet("background:none")
        self.lyricsHLayout = QtWidgets.QVBoxLayout(self.lyricsHeader)
        self.lyricsHeading = QtWidgets.QLabel(parent=self.lyricsHeader, text = "Lyrics")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(500)
        self.lyricsHeading.setStyleSheet("color:#fff")
        self.lyricsHeading.setFont(font)
        self.lyricsHLayout.addWidget(self.lyricsHeading)
        self.lyricsBody = QtWidgets.QWidget(parent=self.lyricsPage)
        self.lyricsBLayout = QtWidgets.QHBoxLayout(self.lyricsBody)
        self.lScrollArea = QtWidgets.QScrollArea(parent=self.lyricsBody)
        self.lyricsBLayout.addWidget(self.lScrollArea)
        self.lScrollArea.setWidgetResizable(True)
        self.lScrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.lScrollWidget = QtWidgets.QWidget()
        self.lScrollWidget.setStyleSheet("background:none;border:none")
        self.lScrollArea.setStyleSheet("border:none")
        self.lScrollArea.setWidget(self.lScrollWidget)
        self.lyricsMain = QtWidgets.QLabel(parent=self.lScrollWidget)
        self.scrollLayout = QtWidgets.QVBoxLayout(self.lScrollWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lyricsMain.setFont(font)
        self.lyricsMain.setStyleSheet("background:none;color:#fff;border:none")
        self.scrollLayout.addWidget(self.lyricsMain)
        self.lyricsPLayout.addWidget(self.lyricsHeader)
        self.lyricsPLayout.addWidget(self.lyricsBody)
        self.lyricsHLayout.setContentsMargins(0, 0, 0, 0)
        self.lyricsHLayout.setSpacing(0)
        self.lyricsBLayout.setContentsMargins(0, 0, 0, 0)
        self.lyricsBLayout.setSpacing(0)
        self.scrollLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollLayout.setSpacing(0)
        self.main.addWidget(self.lyricsPage)
        
        self.horizontalLayout.addWidget(self.main)
        self.main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)